import type { Metadata } from "next";
import "./globals.css";
import BgImg from "@/components/bg-img";


export const metadata: Metadata = {
  title: "Christian Nystad Bergh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <BgImg/>
        {children}</body>
    </html>
  );
}
